Fix bug with displaying the feedback text and update firebase hosting
yeatmanlab/roar-anb pull request #7
Opened 2022-11-17 22:49 UTC by Mohammed-Shoaib

2022-11-22 06:28 UTC, Mohammed-Shoaib commented
Updated PR by integrating the roar-utils package and adding auditory feedback.

2022-11-29 00:26 UTC, richford requested changes
Can you add the `.firebase` folder to .gitignore and remove it? It's not a security risk to have it in git history but we don't need to track it under version control either.

Other than that, LGTM!

2022-11-29 19:47 UTC, Mohammed-Shoaib commented
Thank you for the review @richford! Updated by removing the `.firebase` folder.

2022-11-29 19:57 UTC, richford approved these changes

2022-11-29 19:57 UTC, merged